const { v4: uuidv4 } = require('uuid');

const CARBON_FACTOR_KG_PER_KWH = 0.417;

// ---------------------------------------------------------------------
// Module 2: Predictive Maintenance - asset + maintenance history seeding
// ---------------------------------------------------------------------

const ASSET_CATALOG = [
  { name: 'Main Chiller Unit', type: 'HVAC - Chiller' },
  { name: 'HVAC Unit A', type: 'HVAC - Air Handler' },
  { name: 'HVAC Unit B', type: 'HVAC - Air Handler' },
  { name: 'Main Generator', type: 'Power - Backup Generator' },
  { name: 'Elevator Bank 1', type: 'Vertical Transport' },
  { name: 'Elevator Bank 2', type: 'Vertical Transport' },
  { name: 'Water Pump Station', type: 'Plumbing - Pump' },
  { name: 'Fire Suppression System', type: 'Life Safety' },
  { name: 'Cooling Tower', type: 'HVAC - Cooling Tower' },
  { name: 'Rooftop AHU 3', type: 'HVAC - Air Handler' },
  { name: 'Emergency Lighting Panel', type: 'Electrical - Panel' },
  { name: 'Boiler Unit 1', type: 'HVAC - Boiler' },
];

/**
 * Generates a realistic asset roster for a facility. Health scores are
 * NOT set here - MaintenanceAgent.evaluateAssetHealth() derives them from
 * installDate + a deterministic stress factor, so this generator only
 * needs to produce a believable spread of equipment ages. ~30% of assets
 * are seeded "aging" (6-14 years old) so a fresh seed always surfaces a
 * few genuinely at-risk assets for the predictive cycle to catch.
 *
 * @param {string} facilityId
 * @param {number} count number of assets to generate
 * @param {number} offset starting catalog index - pass the facility's
 *   current asset count when appending, so names don't collide with an
 *   existing roster (e.g. "HVAC Unit A" vs "HVAC Unit A (2)")
 * @returns {Array} Asset-shaped documents (without _id)
 */
function generateAssetsForFacility(facilityId, count = 10, offset = 0) {
  const assets = [];
  const now = Date.now();

  for (let n = 0; n < count; n += 1) {
    const i = offset + n;
    const template = ASSET_CATALOG[i % ASSET_CATALOG.length];
    const cycleNumber = Math.floor(i / ASSET_CATALOG.length);
    const assetName = cycleNumber > 0 ? `${template.name} (${cycleNumber + 1})` : template.name;

    const isAging = Math.random() < 0.3;
    const ageYears = isAging ? 6 + Math.random() * 8 : 0.5 + Math.random() * 4.5;
    const installDate = new Date(now - ageYears * 365 * 24 * 60 * 60 * 1000);

    assets.push({
      assetId: uuidv4(),
      facilityId,
      assetName,
      assetType: template.type,
      installDate,
      status: 'Operational', // recomputed on the first predictive cycle
      healthScore: 100, // placeholder, overwritten immediately after seeding
    });
  }

  return assets;
}

/**
 * Backfills a handful of completed MaintenanceRecord entries for a subset
 * of already-inserted assets, mixing auto-generated (predictive) and
 * manually-scheduled (routine) history. This gives the Downtime Reduction
 * KPI real completed-ticket data to compute against immediately after
 * seeding, rather than reading 0% until real tickets are closed later.
 *
 * @param {Array} assets inserted Asset documents (need assetId, facilityId, assetType)
 * @returns {Promise<Array>} the inserted MaintenanceRecord documents
 */
async function generateMaintenanceHistory(assets) {
  const MaintenanceRecord = require('../models/MaintenanceRecord');
  const now = Date.now();
  const records = [];

  assets.forEach((asset) => {
    if (Math.random() > 0.4) return; // ~40% of assets have prior completed history

    const historyCount = 1 + Math.floor(Math.random() * 2); // 1-2 past records
    for (let i = 0; i < historyCount; i += 1) {
      const daysAgo = 20 + Math.random() * 160;
      const maintenanceDate = new Date(now - daysAgo * 24 * 60 * 60 * 1000);
      const autoGenerated = Math.random() < 0.6;

      records.push({
        maintenanceId: uuidv4(),
        assetId: asset.assetId,
        facilityId: asset.facilityId,
        issueType: autoGenerated ? `Predictive maintenance — ${asset.assetType}` : `Routine service — ${asset.assetType}`,
        maintenanceDate,
        predictedFailureDate: autoGenerated ? new Date(maintenanceDate.getTime() + 3 * 24 * 60 * 60 * 1000) : null,
        status: 'Completed',
        metadata: { autoGenerated, historical: true },
        sourceAgent: autoGenerated ? 'MaintenanceAgent' : 'Manual',
      });
    }
  });

  if (!records.length) return [];
  return MaintenanceRecord.insertMany(records);
}

// ---------------------------------------------------------------------
// Module 3: Occupancy Agent - zone + occupancy log seeding
// ---------------------------------------------------------------------

// Matches the wireframe's Zone Occupancy Distribution exactly. Each zone
// gets a target utilization used to shape its seeded history - Office
// Floors and Meeting Rooms run hotter during business hours than Common
// Areas and Parking.
const ZONE_CATALOG = [
  { name: 'Office Floors', zoneType: 'Workspace', maxCapacity: 220, targetUtilizationPct: 80 },
  { name: 'Meeting Rooms', zoneType: 'Meeting Room', maxCapacity: 60, targetUtilizationPct: 62 },
  { name: 'Common Areas', zoneType: 'Common Area', maxCapacity: 150, targetUtilizationPct: 45 },
  { name: 'Parking Areas', zoneType: 'Parking', maxCapacity: 300, targetUtilizationPct: 35 },
];

/**
 * Generates the 4 canonical zones for a facility. `currentOccupancy`
 * starts at 0 - OccupancyAgent.refreshCurrentOccupancy() sets it from
 * the most recent seeded OccupancyLog right after insertion.
 *
 * @param {string} facilityId
 * @returns {Array} Zone-shaped documents (without _id)
 */
function generateZonesForFacility(facilityId) {
  return ZONE_CATALOG.map((z) => ({
    zoneId: uuidv4(),
    facilityId,
    name: z.name,
    zoneType: z.zoneType,
    maxCapacity: z.maxCapacity,
    currentOccupancy: 0,
  }));
}

/**
 * Generates hourly OccupancyLog history for a set of already-inserted
 * zones, using the same daily occupancy curve shape as the Energy
 * generator (_occupancyCurve) scaled to each zone's target utilization,
 * plus a small chance of an overcrowding spike so the overcrowding
 * detector has something real to catch on a fresh seed.
 *
 * @param {Array} zones inserted Zone documents (need zoneId, facilityId, maxCapacity)
 * @param {number} days hours of history = days * 24
 * @returns {Array} OccupancyLog-shaped documents (without _id)
 */
function generateOccupancyLogsForZones(zones, days = 14) {
  const logs = [];
  const now = new Date();
  const totalHours = days * 24;

  zones.forEach((zone) => {
    const catalogEntry = ZONE_CATALOG.find((z) => z.name === zone.name);
    const targetUtilizationPct = catalogEntry ? catalogEntry.targetUtilizationPct : 50;
    const spikeChance = 0.02; // ~2% of hourly readings spike toward/over capacity

    for (let i = 0; i < totalHours; i += 1) {
      const timestamp = new Date(now.getTime() - (totalHours - i) * 60 * 60 * 1000);
      const hour = timestamp.getHours();
      const dayOfWeek = timestamp.getDay();
      const isWeekend = dayOfWeek === 0 || dayOfWeek === 6;

      const occupancyFactor = _occupancyCurve(hour) * (isWeekend ? 0.3 : 1);
      let utilizationPct = targetUtilizationPct * occupancyFactor * (1 + (Math.random() - 0.5) * 0.3);

      if (Math.random() < spikeChance) {
        utilizationPct = 90 + Math.random() * 20; // 90-110% of capacity
      }

      const recordedOccupancy = Math.max(0, Math.round((utilizationPct / 100) * zone.maxCapacity));

      logs.push({
        logId: uuidv4(),
        zoneId: zone.zoneId,
        facilityId: zone.facilityId,
        timestamp,
        recordedOccupancy,
      });
    }
  });

  return logs;
}

/**
 * Generates a realistic hourly time-series of IoT/utility readings for a
 * facility, including a daily occupancy-driven load curve, weekday/weekend
 * variation, and a small number of injected anomaly spikes so the
 * EnergyAgent's anomaly detector has something meaningful to catch.
 *
 * @param {string} facilityId
 * @param {number} days number of days of hourly history to generate
 * @returns {Array} EnergyUsage-shaped documents (without _id)
 */
function generateReadingsForFacility(facilityId, days = 14) {
  const readings = [];
  const now = new Date();
  const totalHours = days * 24;

  // Randomize a per-facility "personality" so seeded facilities don't all
  // look identical.
  const baseLoadKwh = 15 + Math.random() * 10; // overnight baseline
  const peakLoadKwh = 55 + Math.random() * 25; // occupied-hours peak
  const anomalyCount = Math.max(2, Math.round(totalHours * 0.015)); // ~1.5% of readings
  const anomalyIndices = new Set();
  while (anomalyIndices.size < anomalyCount) {
    anomalyIndices.add(Math.floor(Math.random() * totalHours));
  }

  for (let i = 0; i < totalHours; i += 1) {
    const timestamp = new Date(now.getTime() - (totalHours - i) * 60 * 60 * 1000);
    const hour = timestamp.getHours();
    const dayOfWeek = timestamp.getDay(); // 0 = Sunday
    const isWeekend = dayOfWeek === 0 || dayOfWeek === 6;

    // Occupancy-shaped daily curve: ramps up ~7am, peaks midday, tapers by 7pm.
    const occupancyFactor = _occupancyCurve(hour) * (isWeekend ? 0.35 : 1);

    let electricityUsage = baseLoadKwh + (peakLoadKwh - baseLoadKwh) * occupancyFactor;
    // Natural sensor noise.
    electricityUsage += (Math.random() - 0.5) * 4;

    const hvacShare = 0.42 + Math.random() * 0.08; // ~42-50% of load
    const lightingShare = 0.24 + Math.random() * 0.06; // ~24-30%
    const equipmentShare = 1 - hvacShare - lightingShare;

    let hvacPowerUsage = electricityUsage * hvacShare;
    let lightingPowerUsage = electricityUsage * lightingShare;
    const equipmentPowerUsage = Math.max(0, electricityUsage * equipmentShare);

    // Inject anomaly spikes/drops on selected indices.
    if (anomalyIndices.has(i)) {
      const spike = Math.random() > 0.25; // mostly spikes, occasionally drops
      const magnitude = 1.6 + Math.random() * 1.2; // 1.6x - 2.8x
      if (spike) {
        electricityUsage *= magnitude;
        hvacPowerUsage *= magnitude;
      } else {
        electricityUsage *= 0.3;
        hvacPowerUsage *= 0.3;
      }
    }

    electricityUsage = Math.max(2, electricityUsage);
    hvacPowerUsage = Math.max(0, hvacPowerUsage);
    lightingPowerUsage = Math.max(0, lightingPowerUsage);

    const waterUsage = 80 + occupancyFactor * 220 + (Math.random() - 0.5) * 20;
    const carbonEmissions = electricityUsage * CARBON_FACTOR_KG_PER_KWH;

    readings.push({
      energyId: uuidv4(),
      facilityId,
      timestamp,
      electricityUsage: Number(electricityUsage.toFixed(2)),
      waterUsage: Number(Math.max(10, waterUsage).toFixed(2)),
      hvacPowerUsage: Number(hvacPowerUsage.toFixed(2)),
      lightingPowerUsage: Number(lightingPowerUsage.toFixed(2)),
      equipmentPowerUsage: Number(equipmentPowerUsage.toFixed(2)),
      carbonEmissions: Number(carbonEmissions.toFixed(2)),
    });
  }

  return readings;
}

function _occupancyCurve(hour) {
  // Smooth bell-shaped curve peaking around 1-2 PM, near-zero at 2-4 AM.
  const peakHour = 13;
  const spread = 5.5;
  const value = Math.exp(-((hour - peakHour) ** 2) / (2 * spread ** 2));
  return Math.max(0.08, value); // small nighttime baseline load
}

// ---------------------------------------------------------------------
// Module 4: Security Agent - security event + visitor seeding
// ---------------------------------------------------------------------

const SECURITY_LOCATIONS = ['Main Entrance', 'Lobby', 'Parking Garage', 'Loading Dock', 'Server Room', 'Rear Exit'];

// Realistic mix: mostly routine CCTV noise and the occasional denied
// badge, with a small chance of an actual breach-worthy event so
// detectBreach() has something real to catch on a fresh seed.
const EVENT_TYPE_WEIGHTS = [
  { type: 'CCTV_ANOMALY', severity: 'Low', weight: 45 },
  { type: 'BADGE_DENIED', severity: 'Low', weight: 30 },
  { type: 'DOOR_FORCED_OPEN', severity: 'Medium', weight: 10 },
  { type: 'UNAUTHORIZED_ACCESS', severity: 'Critical', weight: 8 },
  { type: 'TAILGATING', severity: 'High', weight: 7 },
];

function _weightedRandomEventType() {
  const totalWeight = EVENT_TYPE_WEIGHTS.reduce((sum, e) => sum + e.weight, 0);
  let roll = Math.random() * totalWeight;
  for (const entry of EVENT_TYPE_WEIGHTS) {
    if (roll < entry.weight) return entry;
    roll -= entry.weight;
  }
  return EVENT_TYPE_WEIGHTS[0];
}

/**
 * Generates historical SecurityEvent entries for a facility - roughly
 * 3-6 events per day across the given window, weighted toward routine
 * noise with occasional genuine breach events.
 *
 * @param {string} facilityId
 * @param {number} days
 * @returns {Array} SecurityEvent-shaped documents (without _id)
 */
function generateSecurityEventsForFacility(facilityId, days = 14) {
  const events = [];
  const now = Date.now();

  for (let d = 0; d < days; d += 1) {
    const eventsToday = 3 + Math.floor(Math.random() * 4); // 3-6 per day
    for (let i = 0; i < eventsToday; i += 1) {
      const { type, severity } = _weightedRandomEventType();
      const location = SECURITY_LOCATIONS[Math.floor(Math.random() * SECURITY_LOCATIONS.length)];
      const timestamp = new Date(now - (days - d) * 24 * 60 * 60 * 1000 - Math.random() * 24 * 60 * 60 * 1000);

      events.push({
        eventId: uuidv4(),
        facilityId,
        eventType: type,
        location,
        timestamp,
        severity,
        status: 'Resolved', // historical events default resolved; recent ones get reopened below
      });
    }
  }

  // Leave the most recent few events open/investigating so the dashboard
  // and detectBreach() have live, unresolved data to work with immediately.
  events
    .sort((a, b) => b.timestamp - a.timestamp)
    .slice(0, 4)
    .forEach((e) => {
      e.status = e.severity === 'Critical' || e.severity === 'High' ? 'Open' : 'Investigating';
    });

  return events;
}

const VISITOR_NAMES = ['Jordan Lee', 'Casey Kim', 'Morgan Patel', 'Riley Chen', 'Taylor Brooks', 'Alex Rivera', 'Sam Okafor', 'Jamie Novak'];
const VISITOR_LOCATIONS = ['Office Floors', 'Meeting Rooms', 'Common Areas', 'Lobby'];

/**
 * Generates a visitor roster with a realistic mix of currently-checked-in,
 * already-checked-out, and deliberately overdue visitors (expectedCheckOut
 * in the past but status still CheckedIn) so
 * SecurityAgent.refreshVisitorStatuses() has something to flag as
 * Overstayed on the very first cycle run.
 *
 * @param {string} facilityId
 * @param {number} count
 * @returns {Array} Visitor-shaped documents (without _id)
 */
function generateVisitorsForFacility(facilityId, count = 8) {
  const now = Date.now();
  const visitors = [];

  for (let i = 0; i < count; i += 1) {
    const name = VISITOR_NAMES[i % VISITOR_NAMES.length];
    const location = VISITOR_LOCATIONS[Math.floor(Math.random() * VISITOR_LOCATIONS.length)];
    const hoursAgoCheckedIn = 1 + Math.random() * 6; // checked in 1-7 hours ago
    const checkInTime = new Date(now - hoursAgoCheckedIn * 60 * 60 * 1000);
    const visitDurationHours = 1 + Math.random() * 3; // expected 1-4 hour visit
    const expectedCheckOut = new Date(checkInTime.getTime() + visitDurationHours * 60 * 60 * 1000);

    const outcome = Math.random();
    let status = 'CheckedIn';
    let actualCheckOutTime = null;

    if (outcome < 0.25) {
      // already left, on time
      status = 'CheckedOut';
      actualCheckOutTime = new Date(Math.min(now, expectedCheckOut.getTime() + Math.random() * 30 * 60 * 1000));
    } else if (outcome < 0.4 && expectedCheckOut.getTime() < now) {
      // deliberately overdue - still "CheckedIn" until refreshVisitorStatuses() catches it
      status = 'CheckedIn';
    }

    visitors.push({
      visitorId: uuidv4(),
      facilityId,
      name,
      checkInTime,
      expectedCheckOut,
      actualCheckOutTime,
      currentLocation: status === 'CheckedOut' ? null : location,
      status,
    });
  }

  return visitors;
}

/**
 * Standalone CLI seeding entrypoint: `npm run seed`.
 * Creates a handful of demo facilities (if none exist) and populates
 * 14 days of hourly energy history for each.
 */
async function runStandaloneSeed() {
  const mongoose = require('mongoose');
  const connectDB = require('../config/db');
  const Facility = require('../models/Facility');
  const EnergyUsage = require('../models/EnergyUsage');
  const Asset = require('../models/Asset');
  const Zone = require('../models/Zone');
  const OccupancyLog = require('../models/OccupancyLog');
  const SecurityEvent = require('../models/SecurityEvent');
  const Visitor = require('../models/Visitor');
  const MaintenanceAgent = require('../agents/MaintenanceAgent');
  const OccupancyAgent = require('../agents/OccupancyAgent');
  const SecurityAgent = require('../agents/SecurityAgent');

  await connectDB();
  const maintenanceAgent = new MaintenanceAgent();
  const occupancyAgent = new OccupancyAgent();
  const securityAgent = new SecurityAgent();

  const demoFacilities = [
    { facilityName: 'Riverside Tech Campus', facilityType: 'IT Park', location: 'Austin, TX' },
    { facilityName: 'Midtown Corporate Tower', facilityType: 'Office', location: 'Chicago, IL' },
    { facilityName: 'Lakeside General Hospital', facilityType: 'Hospital', location: 'Portland, OR' },
  ];

  for (const def of demoFacilities) {
    let facility = await Facility.findOne({ facilityName: def.facilityName });
    if (!facility) {
      facility = await Facility.create(def);
      console.log(`[seed] Created facility: ${facility.facilityName} (${facility.facilityId})`);
    }

    const existingEnergyCount = await EnergyUsage.countDocuments({ facilityId: facility.facilityId });
    if (existingEnergyCount > 0) {
      console.log(`[seed] Skipping energy readings for ${facility.facilityName}, already has ${existingEnergyCount}`);
    } else {
      const readings = generateReadingsForFacility(facility.facilityId, 14);
      await EnergyUsage.insertMany(readings);
      console.log(`[seed] Inserted ${readings.length} readings for ${facility.facilityName}`);
    }

    const existingAssetCount = await Asset.countDocuments({ facilityId: facility.facilityId });
    if (existingAssetCount > 0) {
      console.log(`[seed] Skipping assets for ${facility.facilityName}, already has ${existingAssetCount}`);
    } else {
      const assetDefs = generateAssetsForFacility(facility.facilityId, 10);
      const assets = await Asset.insertMany(assetDefs);
      await generateMaintenanceHistory(assets);

      const cycle = await maintenanceAgent.runPredictiveCycle(facility.facilityId);
      console.log(
        `[seed] Seeded ${assets.length} assets for ${facility.facilityName}; predictive cycle flagged ${cycle.predictions.length} at-risk asset(s), created ${cycle.workOrdersCreated} work order(s).`
      );
    }

    const existingZoneCount = await Zone.countDocuments({ facilityId: facility.facilityId });
    if (existingZoneCount > 0) {
      console.log(`[seed] Skipping zones for ${facility.facilityName}, already has ${existingZoneCount}`);
    } else {
      const zoneDefs = generateZonesForFacility(facility.facilityId);
      const zones = await Zone.insertMany(zoneDefs);
      const logs = generateOccupancyLogsForZones(zones, 14);
      await OccupancyLog.insertMany(logs);

      const occCycle = await occupancyAgent.runOccupancyCycle(facility.facilityId);
      console.log(
        `[seed] Seeded ${zones.length} zones + ${logs.length} occupancy logs for ${facility.facilityName}; ${occCycle.overcrowded.length} zone(s) currently overcrowded.`
      );
    }

    const existingSecurityCount = await SecurityEvent.countDocuments({ facilityId: facility.facilityId });
    if (existingSecurityCount > 0) {
      console.log(`[seed] Skipping security events for ${facility.facilityName}, already has ${existingSecurityCount}`);
    } else {
      const eventDefs = generateSecurityEventsForFacility(facility.facilityId, 14);
      await SecurityEvent.insertMany(eventDefs);

      const existingVisitorCount = await Visitor.countDocuments({ facilityId: facility.facilityId });
      let visitors = [];
      if (existingVisitorCount === 0) {
        const visitorDefs = generateVisitorsForFacility(facility.facilityId, 8);
        visitors = await Visitor.insertMany(visitorDefs);
      }

      const secCycle = await securityAgent.runSecurityCycle(facility.facilityId);
      console.log(
        `[seed] Seeded ${eventDefs.length} security events + ${visitors.length} visitors for ${facility.facilityName}; ${secCycle.breaches.length} active breach(es), ${secCycle.overstayed.length} overstayed visitor(s).`
      );
    }
  }

  console.log('[seed] Done.');
  await mongoose.connection.close();
  process.exit(0);
}

module.exports = {
  generateReadingsForFacility,
  generateAssetsForFacility,
  generateMaintenanceHistory,
  generateZonesForFacility,
  generateOccupancyLogsForZones,
  generateSecurityEventsForFacility,
  generateVisitorsForFacility,
  runStandaloneSeed,
};

// Allow `node seed/mockDataGenerator.js` to run the standalone seed directly.
if (require.main === module) {
  runStandaloneSeed().catch((err) => {
    console.error('[seed] Failed:', err);
    process.exit(1);
  });
}
