const { v4: uuidv4 } = require('uuid');

const CARBON_FACTOR_KG_PER_KWH = 0.417;

// ---------------------------------------------------------------------
// Module 2: Predictive Maintenance - asset + maintenance history seeding
// ---------------------------------------------------------------------

const ASSET_CATALOG = [
  { name: 'Main Chiller Unit', type: 'HVAC - Chiller' },
  { name: 'HVAC Unit A', type: 'HVAC - Air Handler' },
  { name: 'HVAC Unit B', type: 'HVAC - Air Handler' },
  { name: 'Main Generator', type: 'Power - Backup Generator' },
  { name: 'Elevator Bank 1', type: 'Vertical Transport' },
  { name: 'Elevator Bank 2', type: 'Vertical Transport' },
  { name: 'Water Pump Station', type: 'Plumbing - Pump' },
  { name: 'Fire Suppression System', type: 'Life Safety' },
  { name: 'Cooling Tower', type: 'HVAC - Cooling Tower' },
  { name: 'Rooftop AHU 3', type: 'HVAC - Air Handler' },
  { name: 'Emergency Lighting Panel', type: 'Electrical - Panel' },
  { name: 'Boiler Unit 1', type: 'HVAC - Boiler' },
];

/**
 * Generates a realistic asset roster for a facility. Health scores are
 * NOT set here - MaintenanceAgent.evaluateAssetHealth() derives them from
 * installDate + a deterministic stress factor, so this generator only
 * needs to produce a believable spread of equipment ages. ~30% of assets
 * are seeded "aging" (6-14 years old) so a fresh seed always surfaces a
 * few genuinely at-risk assets for the predictive cycle to catch.
 *
 * @param {string} facilityId
 * @param {number} count number of assets to generate
 * @returns {Array} Asset-shaped documents (without _id)
 */
function generateAssetsForFacility(facilityId, count = 10) {
  const assets = [];
  const now = Date.now();

  for (let i = 0; i < count; i += 1) {
    const template = ASSET_CATALOG[i % ASSET_CATALOG.length];
    const cycleNumber = Math.floor(i / ASSET_CATALOG.length);
    const assetName = cycleNumber > 0 ? `${template.name} (${cycleNumber + 1})` : template.name;

    const isAging = Math.random() < 0.3;
    const ageYears = isAging ? 6 + Math.random() * 8 : 0.5 + Math.random() * 4.5;
    const installDate = new Date(now - ageYears * 365 * 24 * 60 * 60 * 1000);

    assets.push({
      assetId: uuidv4(),
      facilityId,
      assetName,
      assetType: template.type,
      installDate,
      status: 'Operational', // recomputed on the first predictive cycle
      healthScore: 100, // placeholder, overwritten immediately after seeding
    });
  }

  return assets;
}

/**
 * Backfills a handful of completed MaintenanceRecord entries for a subset
 * of already-inserted assets, mixing auto-generated (predictive) and
 * manually-scheduled (routine) history. This gives the Downtime Reduction
 * KPI real completed-ticket data to compute against immediately after
 * seeding, rather than reading 0% until real tickets are closed later.
 *
 * @param {Array} assets inserted Asset documents (need assetId, facilityId, assetType)
 * @returns {Promise<Array>} the inserted MaintenanceRecord documents
 */
async function generateMaintenanceHistory(assets) {
  const MaintenanceRecord = require('../models/MaintenanceRecord');
  const now = Date.now();
  const records = [];

  assets.forEach((asset) => {
    if (Math.random() > 0.4) return; // ~40% of assets have prior completed history

    const historyCount = 1 + Math.floor(Math.random() * 2); // 1-2 past records
    for (let i = 0; i < historyCount; i += 1) {
      const daysAgo = 20 + Math.random() * 160;
      const maintenanceDate = new Date(now - daysAgo * 24 * 60 * 60 * 1000);
      const autoGenerated = Math.random() < 0.6;

      records.push({
        maintenanceId: uuidv4(),
        assetId: asset.assetId,
        facilityId: asset.facilityId,
        issueType: autoGenerated ? `Predictive maintenance — ${asset.assetType}` : `Routine service — ${asset.assetType}`,
        maintenanceDate,
        predictedFailureDate: autoGenerated ? new Date(maintenanceDate.getTime() + 3 * 24 * 60 * 60 * 1000) : null,
        status: 'Completed',
        metadata: { autoGenerated, historical: true },
        sourceAgent: autoGenerated ? 'MaintenanceAgent' : 'Manual',
      });
    }
  });

  if (!records.length) return [];
  return MaintenanceRecord.insertMany(records);
}

/**
 * Generates a realistic hourly time-series of IoT/utility readings for a
 * facility, including a daily occupancy-driven load curve, weekday/weekend
 * variation, and a small number of injected anomaly spikes so the
 * EnergyAgent's anomaly detector has something meaningful to catch.
 *
 * @param {string} facilityId
 * @param {number} days number of days of hourly history to generate
 * @returns {Array} EnergyUsage-shaped documents (without _id)
 */
function generateReadingsForFacility(facilityId, days = 14) {
  const readings = [];
  const now = new Date();
  const totalHours = days * 24;

  // Randomize a per-facility "personality" so seeded facilities don't all
  // look identical.
  const baseLoadKwh = 15 + Math.random() * 10; // overnight baseline
  const peakLoadKwh = 55 + Math.random() * 25; // occupied-hours peak
  const anomalyCount = Math.max(2, Math.round(totalHours * 0.015)); // ~1.5% of readings
  const anomalyIndices = new Set();
  while (anomalyIndices.size < anomalyCount) {
    anomalyIndices.add(Math.floor(Math.random() * totalHours));
  }

  for (let i = 0; i < totalHours; i += 1) {
    const timestamp = new Date(now.getTime() - (totalHours - i) * 60 * 60 * 1000);
    const hour = timestamp.getHours();
    const dayOfWeek = timestamp.getDay(); // 0 = Sunday
    const isWeekend = dayOfWeek === 0 || dayOfWeek === 6;

    // Occupancy-shaped daily curve: ramps up ~7am, peaks midday, tapers by 7pm.
    const occupancyFactor = _occupancyCurve(hour) * (isWeekend ? 0.35 : 1);

    let electricityUsage = baseLoadKwh + (peakLoadKwh - baseLoadKwh) * occupancyFactor;
    // Natural sensor noise.
    electricityUsage += (Math.random() - 0.5) * 4;

    const hvacShare = 0.42 + Math.random() * 0.08; // ~42-50% of load
    const lightingShare = 0.24 + Math.random() * 0.06; // ~24-30%
    const equipmentShare = 1 - hvacShare - lightingShare;

    let hvacPowerUsage = electricityUsage * hvacShare;
    let lightingPowerUsage = electricityUsage * lightingShare;
    const equipmentPowerUsage = Math.max(0, electricityUsage * equipmentShare);

    // Inject anomaly spikes/drops on selected indices.
    if (anomalyIndices.has(i)) {
      const spike = Math.random() > 0.25; // mostly spikes, occasionally drops
      const magnitude = 1.6 + Math.random() * 1.2; // 1.6x - 2.8x
      if (spike) {
        electricityUsage *= magnitude;
        hvacPowerUsage *= magnitude;
      } else {
        electricityUsage *= 0.3;
        hvacPowerUsage *= 0.3;
      }
    }

    electricityUsage = Math.max(2, electricityUsage);
    hvacPowerUsage = Math.max(0, hvacPowerUsage);
    lightingPowerUsage = Math.max(0, lightingPowerUsage);

    const waterUsage = 80 + occupancyFactor * 220 + (Math.random() - 0.5) * 20;
    const carbonEmissions = electricityUsage * CARBON_FACTOR_KG_PER_KWH;

    readings.push({
      energyId: uuidv4(),
      facilityId,
      timestamp,
      electricityUsage: Number(electricityUsage.toFixed(2)),
      waterUsage: Number(Math.max(10, waterUsage).toFixed(2)),
      hvacPowerUsage: Number(hvacPowerUsage.toFixed(2)),
      lightingPowerUsage: Number(lightingPowerUsage.toFixed(2)),
      equipmentPowerUsage: Number(equipmentPowerUsage.toFixed(2)),
      carbonEmissions: Number(carbonEmissions.toFixed(2)),
    });
  }

  return readings;
}

function _occupancyCurve(hour) {
  // Smooth bell-shaped curve peaking around 1-2 PM, near-zero at 2-4 AM.
  const peakHour = 13;
  const spread = 5.5;
  const value = Math.exp(-((hour - peakHour) ** 2) / (2 * spread ** 2));
  return Math.max(0.08, value); // small nighttime baseline load
}

/**
 * Standalone CLI seeding entrypoint: `npm run seed`.
 * Creates a handful of demo facilities (if none exist) and populates
 * 14 days of hourly energy history for each.
 */
async function runStandaloneSeed() {
  const mongoose = require('mongoose');
  const connectDB = require('../config/db');
  const Facility = require('../models/Facility');
  const EnergyUsage = require('../models/EnergyUsage');
  const Asset = require('../models/Asset');
  const MaintenanceAgent = require('../agents/MaintenanceAgent');

  await connectDB();
  const maintenanceAgent = new MaintenanceAgent();

  const demoFacilities = [
    { facilityName: 'Riverside Tech Campus', facilityType: 'IT Park', location: 'Austin, TX' },
    { facilityName: 'Midtown Corporate Tower', facilityType: 'Office', location: 'Chicago, IL' },
    { facilityName: 'Lakeside General Hospital', facilityType: 'Hospital', location: 'Portland, OR' },
  ];

  for (const def of demoFacilities) {
    let facility = await Facility.findOne({ facilityName: def.facilityName });
    if (!facility) {
      facility = await Facility.create(def);
      console.log(`[seed] Created facility: ${facility.facilityName} (${facility.facilityId})`);
    }

    const existingCount = await EnergyUsage.countDocuments({ facilityId: facility.facilityId });
    if (existingCount > 0) {
      console.log(`[seed] Skipping ${facility.facilityName}, already has ${existingCount} readings`);
      continue;
    }

    const readings = generateReadingsForFacility(facility.facilityId, 14);
    await EnergyUsage.insertMany(readings);
    console.log(`[seed] Inserted ${readings.length} readings for ${facility.facilityName}`);

    const existingAssetCount = await Asset.countDocuments({ facilityId: facility.facilityId });
    if (existingAssetCount > 0) {
      console.log(`[seed] Skipping assets for ${facility.facilityName}, already has ${existingAssetCount}`);
      continue;
    }

    const assetDefs = generateAssetsForFacility(facility.facilityId, 10);
    const assets = await Asset.insertMany(assetDefs);
    await generateMaintenanceHistory(assets);

    const cycle = await maintenanceAgent.runPredictiveCycle(facility.facilityId);
    console.log(
      `[seed] Seeded ${assets.length} assets for ${facility.facilityName}; predictive cycle flagged ${cycle.predictions.length} at-risk asset(s), created ${cycle.workOrdersCreated} work order(s).`
    );
  }

  console.log('[seed] Done.');
  await mongoose.connection.close();
  process.exit(0);
}

module.exports = {
  generateReadingsForFacility,
  generateAssetsForFacility,
  generateMaintenanceHistory,
  runStandaloneSeed,
};

// Allow `node seed/mockDataGenerator.js` to run the standalone seed directly.
if (require.main === module) {
  runStandaloneSeed().catch((err) => {
    console.error('[seed] Failed:', err);
    process.exit(1);
  });
}
