const Asset = require('../models/Asset');
const MaintenanceRecord = require('../models/MaintenanceRecord');
const MaintenanceAgent = require('../agents/MaintenanceAgent');
const { generateAssetsForFacility, generateMaintenanceHistory } = require('../seed/mockDataGenerator');

const agent = new MaintenanceAgent();

// Assumed hours-of-downtime for a reactive (unplanned, post-failure) repair
// vs. a proactive (scheduled, pre-failure) service visit. Used only to
// express "Downtime Reduction" as an explainable, order-of-magnitude KPI -
// same modeling approach as the cost/carbon estimates in the Energy module.
const REACTIVE_DOWNTIME_HOURS = 16;
const PROACTIVE_DOWNTIME_HOURS = 4;

/**
 * @route GET /api/maintenance/:facilityId/summary
 * KPI cards: assets monitored, active tickets, predicted failures, downtime reduction.
 */
async function getSummary(req, res) {
  try {
    const { facilityId } = req.params;

    const [assetsMonitored, activeTickets, evaluatedAssets, completedRecords] = await Promise.all([
      Asset.countDocuments({ facilityId }),
      MaintenanceRecord.countDocuments({ facilityId, status: { $in: ['Pending', 'In Progress'] } }),
      agent.evaluateFacilityAssets(facilityId),
      MaintenanceRecord.find({ facilityId, status: 'Completed' }).lean(),
    ]);

    const predictions = agent.predictFailures(evaluatedAssets);

    const completedProactive = completedRecords.filter((r) => r.metadata?.autoGenerated).length;
    const totalCompleted = completedRecords.length;
    const downtimeAvoidedHours = completedProactive * (REACTIVE_DOWNTIME_HOURS - PROACTIVE_DOWNTIME_HOURS);
    const baselineDowntimeHours = totalCompleted * REACTIVE_DOWNTIME_HOURS;
    const downtimeReductionPct = baselineDowntimeHours > 0 ? Math.round((downtimeAvoidedHours / baselineDowntimeHours) * 100) : 0;

    res.json({
      success: true,
      data: {
        assetsMonitored,
        activeTickets,
        predictedFailures: predictions.length,
        downtimeReductionPct: Math.max(0, downtimeReductionPct),
      },
    });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
}

/**
 * @route GET /api/maintenance/:facilityId/assets?status=
 * Asset list, used for the health distribution panel and asset browsing.
 */
async function getAssets(req, res) {
  try {
    const { facilityId } = req.params;
    const { status } = req.query;
    const filter = { facilityId };
    if (status) filter.status = status;

    const assets = await Asset.find(filter).sort({ healthScore: 1 }).lean();
    res.json({ success: true, count: assets.length, data: assets });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
}

/**
 * @route GET /api/maintenance/:facilityId/predictions
 * Re-evaluates asset health, then returns failure risk predictions
 * (does NOT create work orders - that's an explicit separate action).
 */
async function getPredictions(req, res) {
  try {
    const { facilityId } = req.params;
    const evaluatedAssets = await agent.evaluateFacilityAssets(facilityId);
    const predictions = agent.predictFailures(evaluatedAssets);
    res.json({ success: true, count: predictions.length, data: predictions });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
}

/**
 * @route GET /api/maintenance/:facilityId/recommendations
 */
async function getRecommendations(req, res) {
  try {
    const { facilityId } = req.params;
    const evaluatedAssets = await agent.evaluateFacilityAssets(facilityId);
    const predictions = agent.predictFailures(evaluatedAssets);
    const recommendations = agent.generateMaintenanceRecommendations(predictions);
    res.json({ success: true, data: recommendations });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
}

/**
 * @route POST /api/maintenance/:facilityId/run-cycle
 * Full autonomous cycle: evaluate -> predict -> auto-generate work orders
 * (+ alerts) for anything inside the risk window.
 */
async function runPredictiveCycle(req, res) {
  try {
    const { facilityId } = req.params;
    const result = await agent.runPredictiveCycle(facilityId);
    res.json({ success: true, data: result });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
}

/**
 * @route POST /api/maintenance/:facilityId/assets/:assetId/work-order
 * Manual "Generate Work Order" action for one asset from the dashboard.
 */
async function createWorkOrder(req, res) {
  try {
    const { assetId } = req.params;
    const result = await agent.createWorkOrderForAsset(assetId);
    res.status(result.alreadyExisted ? 200 : 201).json({ success: true, data: result });
  } catch (err) {
    res.status(err.status || 500).json({ success: false, message: err.message });
  }
}

/**
 * @route GET /api/maintenance/:facilityId/work-orders?status=
 */
async function getWorkOrders(req, res) {
  try {
    const { facilityId } = req.params;
    const { status } = req.query;
    const filter = { facilityId };
    if (status) filter.status = status;

    const workOrders = await MaintenanceRecord.find(filter).sort({ maintenanceDate: 1 }).limit(100).lean();
    res.json({ success: true, count: workOrders.length, data: workOrders });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
}

/**
 * @route PATCH /api/maintenance/work-orders/:maintenanceId
 * Update a ticket's status (Pending -> In Progress -> Completed).
 */
async function updateWorkOrderStatus(req, res) {
  try {
    const { maintenanceId } = req.params;
    const { status } = req.body;

    if (!['Pending', 'In Progress', 'Completed'].includes(status)) {
      return res.status(400).json({ success: false, message: 'Invalid status value' });
    }

    const record = await MaintenanceRecord.findOneAndUpdate({ maintenanceId }, { $set: { status } }, { new: true });
    if (!record) {
      return res.status(404).json({ success: false, message: 'Maintenance record not found' });
    }
    res.json({ success: true, data: record });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
}

/**
 * @route POST /api/maintenance/:facilityId/seed?count=
 * Seeds a realistic asset roster (+ some maintenance history) for a
 * facility, then runs one predictive cycle so the dashboard has
 * predictions/work orders/alerts immediately.
 */
async function seedFacilityAssets(req, res) {
  try {
    const { facilityId } = req.params;
    const count = parseInt(req.query.count, 10) || 10;

    const existing = await Asset.countDocuments({ facilityId });
    if (existing > 0) {
      return res.status(409).json({
        success: false,
        message: `Facility already has ${existing} assets. Delete them first to reseed.`,
      });
    }

    const assetDefs = generateAssetsForFacility(facilityId, count);
    const assets = await Asset.insertMany(assetDefs);

    await generateMaintenanceHistory(assets);

    const cycleResult = await agent.runPredictiveCycle(facilityId);

    res.status(201).json({
      success: true,
      message: `Seeded ${assets.length} assets for facility ${facilityId}`,
      count: assets.length,
      cycleResult,
    });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
}

module.exports = {
  getSummary,
  getAssets,
  getPredictions,
  getRecommendations,
  runPredictiveCycle,
  createWorkOrder,
  getWorkOrders,
  updateWorkOrderStatus,
  seedFacilityAssets,
};
